### PR TITLE
updated AWS SDK to `3.232.2` and added a build directory which is use…

### PR DESCRIPTION
**Pull request by oppiansteve**
…d for updating and automatic namespacing of the AWS SDK and dependencies

approach was as described in https://github.com/andrealandonio/cloud-search/issues/4

### CODE REVIEW

**Comment by oppiansteve** [comment]
I'm currently regression testing this on PHP 7.4 on dev and staging environments of 2 of our servers.

If it passes the testing there, I'll deploy to prod environments of those servers and upgrade to PHP 8, to check it in real usage.

**Comment by oppiansteve** [comment]
sorry, this was left so long - but we've been using this on live systems for quite a while now and seems to be fine.

Note that the `WP_ACS_SEARCH_ENDPOINT` must now have the `https://` prefix  - so if we want to maintain compatibility for this define, we need to check for it and if not present add it on the fly

**Comment by andrealandonio** [comment]
thanks @oppiansteve I'll review your PR in the next days... and thanks again for now :v:

**Comment by andrealandonio** [comment]
Hey @oppiansteve I'm getting a permission error on kaldor/cloud-search.git to andrealandonio.
Could you check if you have unchecked the box in the pull request that says “Allow edits from maintainers”? 
I made a commit for normalizing the acs_search_endpoint field.

Furthermore, I've tested your PR and seems ok, so after that I can merge it ;-)

**Pull request merged**
